export const REGULATORY_SOURCE_RECORDED_AT = new Date('2026-08-18T00:00:00.000Z');

export const REGULATORY_SOURCE_V1 = [
  {
    id: 'a1000000-0000-4000-8000-000000000001',
    sourceKey: 'EC_MDT_2024_196',
    countryCode: 'EC',
    issuer: 'Ministerio del Trabajo',
    documentType: 'MINISTERIAL_AGREEMENT',
    referenceNumber: 'MDT-2024-196',
    canonicalTitle: 'Acuerdo Ministerial Nro. MDT-2024-196',
    candidateStatus: 'TECHNICAL_REVIEW_PENDING',
    officialDocumentLocated: true,
    officialUrl:
      'https://www.trabajo.gob.ec/wp-content/uploads/2024/10/ACUERDO-MINISTERIAL-NRO.-MDT-2024-196-signed.pdf',
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'Documento firmado localizado; requiere revisión técnica y jurídica.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000002',
    sourceKey: 'EC_MDT_2024_196_ANNEX_1',
    countryCode: 'EC',
    issuer: 'Ministerio del Trabajo',
    documentType: 'ANNEX',
    referenceNumber: 'MDT-2024-196-ANEXO-1',
    canonicalTitle: 'Anexo 1 — Lista de Verificación SST',
    candidateStatus: 'TECHNICAL_REVIEW_PENDING',
    officialDocumentLocated: true,
    officialUrl:
      'https://www.trabajo.gob.ec/wp-content/uploads/2025/04/Anexo-1_Lista-de-Verificacion-SST-signed-signed_08042025.pdf',
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'Documento oficial localizado; no se extrajeron preguntas ni obligaciones.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000003',
    sourceKey: 'EC_MDT_2024_196_ANNEX_2',
    countryCode: 'EC',
    issuer: 'Ministerio del Trabajo',
    documentType: 'ANNEX',
    referenceNumber: 'MDT-2024-196-ANEXO-2',
    canonicalTitle: 'Anexo 2 — Nivel de Riesgo',
    candidateStatus: 'OFFICIAL_DOCUMENT_LOCATED',
    officialDocumentLocated: true,
    officialUrl: 'https://www.trabajo.gob.ec/normativa-legal-programas-formatos-y-guias/',
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'El índice oficial enumera el anexo; falta fijar archivo y versión.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000004',
    sourceKey: 'EC_MDT_2024_196_ANNEX_3',
    countryCode: 'EC',
    issuer: 'Ministerio del Trabajo',
    documentType: 'ANNEX',
    referenceNumber: 'MDT-2024-196-ANEXO-3',
    canonicalTitle: 'Anexo 3 — Norma Técnica de Seguridad e Higiene en el Trabajo',
    candidateStatus: 'OFFICIAL_DOCUMENT_LOCATED',
    officialDocumentLocated: true,
    officialUrl: 'https://www.trabajo.gob.ec/normativa-legal-programas-formatos-y-guias/',
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'El índice oficial enumera el anexo; falta fijar documento, versión y alcance.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000005',
    sourceKey: 'EC_EXECUTIVE_DECREE_255',
    countryCode: 'EC',
    issuer: 'Presidencia de la República del Ecuador',
    documentType: 'EXECUTIVE_DECREE',
    referenceNumber: '255',
    canonicalTitle: 'Reglamento de Seguridad y Salud en el Trabajo',
    candidateStatus: 'TECHNICAL_REVIEW_PENDING',
    officialDocumentLocated: true,
    officialUrl: 'https://www.trabajo.gob.ec/reglamento-de-seguridad-y-salud-en-el-trabajo/',
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'Documento candidato localizado; publicación y efecto requieren revisión formal.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000006',
    sourceKey: 'EC_MSP_00004_2026_SISAT',
    countryCode: 'EC',
    issuer: 'Ministerio de Salud Pública',
    documentType: 'MINISTERIAL_AGREEMENT',
    referenceNumber: '00004-2026',
    canonicalTitle: 'Acuerdo MSP 00004-2026 — SISAT',
    candidateStatus: 'DISCOVERED',
    officialDocumentLocated: false,
    officialUrl: null,
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'Referencia candidata para investigación; no usar para extracción ni reglas.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000007',
    sourceKey: 'EC_LABOR_CODE',
    countryCode: 'EC',
    issuer: 'Estado ecuatoriano / Ministerio del Trabajo como repositorio oficial',
    documentType: 'CODE',
    referenceNumber: 'CODIGO_DEL_TRABAJO',
    canonicalTitle: 'Código del Trabajo',
    candidateStatus: 'LEGAL_REVIEW_PENDING',
    officialDocumentLocated: true,
    officialUrl:
      'https://www.trabajo.gob.ec/wp-content/uploads/downloads/2024/01/CODIGO_DEL_TRABAJO.pdf',
    supersessionStatus: 'CURRENT_VERSION_NOT_ESTABLISHED',
    reviewNotes:
      'Copia localizada; consolidación y reformas aplicables requieren revisión jurídica.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000008',
    sourceKey: 'EC_IESS_CD_513',
    countryCode: 'EC',
    issuer: 'Instituto Ecuatoriano de Seguridad Social',
    documentType: 'RESOLUTION',
    referenceNumber: 'C.D. 513',
    canonicalTitle: 'Reglamento del Seguro General de Riesgos del Trabajo',
    candidateStatus: 'DISCOVERED',
    officialDocumentLocated: false,
    officialUrl: null,
    supersessionStatus: 'UNKNOWN_REVIEW_REQUIRED',
    reviewNotes: 'Debe localizarse y fijarse el documento fuente exacto.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000009',
    sourceKey: 'EC_IESS_CD_517',
    countryCode: 'EC',
    issuer: 'Instituto Ecuatoriano de Seguridad Social',
    documentType: 'RESOLUTION',
    referenceNumber: 'C.D. 517',
    canonicalTitle: 'Reglamento General de Responsabilidad Patronal',
    candidateStatus: 'SUPERSESSION_REVIEW_REQUIRED',
    officialDocumentLocated: true,
    officialUrl: 'https://www.iess.gob.ec/es/resoluciones?_110_INSTANCE_Pl7m_fileEntryId=6949406',
    supersessionStatus: 'RELATION_REVIEW_REQUIRED',
    reviewNotes:
      'Documento histórico localizado; su relación con C.D. 677 requiere revisión formal.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000010',
    sourceKey: 'EC_IESS_CD_527_INTERVIEW_REFERENCE',
    countryCode: 'EC',
    issuer: 'Desconocido — referencia de entrevista',
    documentType: 'OTHER',
    referenceNumber: 'C.D. 527',
    canonicalTitle: 'C.D. 527 — título no verificado',
    candidateStatus: 'REJECTED_REFERENCE',
    officialDocumentLocated: false,
    officialUrl: null,
    supersessionStatus: 'UNVERIFIED_REFERENCE',
    reviewNotes: 'Referencia no verificada; no renombrar ni utilizar para reglas.',
  },
  {
    id: 'a1000000-0000-4000-8000-000000000011',
    sourceKey: 'EC_IESS_CD_677',
    countryCode: 'EC',
    issuer: 'Instituto Ecuatoriano de Seguridad Social',
    documentType: 'RESOLUTION',
    referenceNumber: 'C.D. 677',
    canonicalTitle: 'Reglamento General de Responsabilidad Patronal',
    candidateStatus: 'SUPERSESSION_REVIEW_REQUIRED',
    officialDocumentLocated: true,
    officialUrl: 'https://www.iess.gob.ec/documents/10162/33703/C.D.%2B677',
    supersessionStatus: 'RELATION_REVIEW_REQUIRED',
    reviewNotes: 'Documento localizado; su relación con C.D. 517 requiere revisión formal.',
  },
] as const;

export const REGULATORY_SOURCE_RELATIONSHIPS_V1 = [
  {
    id: 'a3000000-0000-4000-8000-000000000001',
    fromSourceKey: 'EC_IESS_CD_517',
    toSourceKey: 'EC_IESS_CD_677',
    relationshipType: 'POSSIBLE_SUPERSESSION',
    reviewStatus: 'PENDING_REVIEW',
    notes: 'Relación pendiente de revisión formal; no establece cuál documento controla.',
  },
] as const;
