import { sstValidationScenarioSchema, type SstValidationScenario } from './schema.js';

function pendingExpert(questions: string[]): SstValidationScenario['expertValidation'] {
  return {
    status: 'PENDING_EXPERT_REVIEW',
    expectedApplicability: null,
    missingInformation: [],
    variablesToAdd: [],
    organizationVsWorkCenterScope: null,
    expectedDepth: null,
    currentStateQuestions: [],
    recommendedNextStep: null,
    confidence: null,
    comments: null,
    agreementWithEngineOutcome: null,
    questions,
  };
}

const scenarioInputs: readonly SstValidationScenario[] = [
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_SMALL_SERVICES',
    name: 'Organización sintética pequeña de servicios',
    description:
      'Oficina de servicios con un solo centro, plantilla reducida y sin procesos químicos ni operaciones de alta energía.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Servicios',
        workCenterCount: 1,
        workerCount: 6,
      },
      operations: { hasChemicalProcesses: false, hasHighEnergyOperations: false },
    },
    organizationContext: {
      summary: 'Operación administrativa sintética de baja complejidad y un solo centro.',
      sizeHypothesis: 'SMALL',
      economicActivitySummary: 'Servicios administrativos generales.',
    },
    workCenters: [
      {
        workCenterId: 'SERVICES_OFFICE',
        displayName: 'Centro sintético de servicios',
        workerCount: 6,
        economicActivities: ['Servicios administrativos'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: ['ELECTRICAL_EXPOSURE'],
      },
    ],
    operationalContext: {
      transportOperations: false,
      workAtHeight: false,
      contractors: false,
      criticalMachinery: false,
      fireExposure: false,
      electricityExposure: true,
      projectChanges: false,
      businessContinuityCriticality: 'LOW',
      qualitySensitivity: 'MEDIUM',
      notes: ['El contexto operativo no altera el input del motor V1.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'ELECTRICITY',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: ['PEOPLE_AND_HEALTH', 'PRODUCT_OR_SERVICE_QUALITY'],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_BASELINE_MANAGEMENT',
        implementationState: 'PARTIALLY_IMPLEMENTED',
        evidence: 'SELF_DECLARED',
        note: 'Declaración sintética pendiente de validación y sin inferencia de cumplimiento.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_1_VISIBLE_OPERATIONAL',
      rationale: 'Hipótesis experta futura para una operación visible y administrativa.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_CHEMICAL_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_HIGH_ENERGY_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'OPTIONAL',
          winningRuleId: 'DEMO_SECTOR_OPTIONAL',
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿El perfil mínimo es suficiente para distinguir una operación administrativa simple?',
      '¿Qué hechos deberían evaluarse a nivel de centro y no de organización?',
      '¿Qué profundidad mínima esperaría una persona especialista?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_MULTI_SITE_SERVICES',
    name: 'Organización sintética de servicios multi-centro',
    description:
      'Servicios distribuidos en tres centros con plantilla superior al umbral puramente demostrativo.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Servicios',
        workCenterCount: 3,
        workerCount: 35,
      },
      operations: { hasChemicalProcesses: false, hasHighEnergyOperations: false },
    },
    organizationContext: {
      summary: 'Operación sintética de servicios con coordinación entre tres centros.',
      sizeHypothesis: 'MEDIUM',
      economicActivitySummary: 'Servicios administrativos y atención operativa distribuida.',
    },
    workCenters: [
      {
        workCenterId: 'SERVICES_CENTER_A',
        displayName: 'Centro sintético de servicios A',
        workerCount: 15,
        economicActivities: ['Administración'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: ['ELECTRICAL_EXPOSURE'],
      },
      {
        workCenterId: 'SERVICES_CENTER_B',
        displayName: 'Centro sintético de servicios B',
        workerCount: 12,
        economicActivities: ['Atención operativa'],
        riskClassificationHypothesis: 'MEDIUM',
        facilityType: 'OFFICE',
        operationalIndicators: ['CONTRACTOR_PRESENCE'],
      },
      {
        workCenterId: 'SERVICES_CENTER_C',
        displayName: 'Centro sintético de servicios C',
        workerCount: 8,
        economicActivities: ['Soporte interno'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: [],
      },
    ],
    operationalContext: {
      transportOperations: false,
      workAtHeight: false,
      contractors: true,
      criticalMachinery: false,
      fireExposure: false,
      electricityExposure: true,
      projectChanges: false,
      businessContinuityCriticality: 'MEDIUM',
      qualitySensitivity: 'MEDIUM',
      notes: ['La distribución de trabajadores por centro no es input de Profile V1.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'CONTRACTORS',
      'BUSINESS_CONTINUITY',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'PRODUCTIVE_CONTINUITY',
      'BUSINESS_CONTINUITY',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_MULTI_SITE_COORDINATION',
        implementationState: 'PLANNED',
        evidence: 'NOTE_AVAILABLE',
        note: 'Plan sintético sin verificación de implementación ni eficacia.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_2_TECHNICAL_SOURCE_BASED',
      rationale:
        'La coordinación multi-centro sugiere revisar evidencia estructurada en el futuro.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_CHEMICAL_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_HIGH_ENERGY_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_MULTI_SITE_RECOMMENDED',
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'OPTIONAL',
          winningRuleId: 'DEMO_SECTOR_OPTIONAL',
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué diferencias por centro deberían cambiar la evaluación futura?',
      '¿La coordinación multi-centro necesita un mínimo de profundidad propio?',
      '¿Qué evidencia sería relevante para validar coordinación real?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_MANUFACTURING_HIGH_ENERGY',
    name: 'Organización sintética manufacturera con alta energía',
    description:
      'Contexto manufacturero sintético con plantilla alta y operaciones de alta energía, sin proceso químico declarado.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Manufactura',
        workCenterCount: 2,
        workerCount: 120,
      },
      operations: { hasChemicalProcesses: false, hasHighEnergyOperations: true },
    },
    organizationContext: {
      summary: 'Manufactura sintética con áreas administrativas y operación de maquinaria.',
      sizeHypothesis: 'LARGE',
      economicActivitySummary: 'Manufactura general y soporte técnico.',
    },
    workCenters: [
      {
        workCenterId: 'MANUFACTURING_PLANT',
        displayName: 'Planta sintética de manufactura',
        workerCount: 100,
        economicActivities: ['Manufactura'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'MANUFACTURING',
        operationalIndicators: [
          'HIGH_ENERGY_EQUIPMENT',
          'CRITICAL_MACHINERY',
          'FIRE_LOAD',
          'ELECTRICAL_EXPOSURE',
        ],
      },
      {
        workCenterId: 'MANUFACTURING_OFFICE',
        displayName: 'Centro sintético administrativo',
        workerCount: 20,
        economicActivities: ['Administración'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: [],
      },
    ],
    operationalContext: {
      transportOperations: false,
      workAtHeight: false,
      contractors: true,
      criticalMachinery: true,
      fireExposure: true,
      electricityExposure: true,
      projectChanges: true,
      businessContinuityCriticality: 'HIGH',
      qualitySensitivity: 'HIGH',
      notes: ['La criticidad de maquinaria no es calculada por Applicability V1.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'CONTRACTORS',
      'CRITICAL_MACHINERY',
      'FIRE_EXPOSURE',
      'ELECTRICITY',
      'BUSINESS_CONTINUITY',
      'QUALITY_SENSITIVITY',
      'PROJECT_CHANGES',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'MACHINERY_AND_INFRASTRUCTURE',
      'PRODUCTIVE_CONTINUITY',
      'PRODUCT_OR_SERVICE_QUALITY',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
        implementationState: 'IN_PROGRESS',
        evidence: 'NOTE_AVAILABLE',
        note: 'Hipótesis sintética; no demuestra control implementado o efectivo.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_3_SYSTEMIC_CHANGE_MANAGEMENT',
      rationale: 'Maquinaria crítica y cambios de proceso justifican discusión sistémica futura.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_CHEMICAL_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NEEDS_EXPERT_REVIEW',
          winningRuleId: 'DEMO_HIGH_ENERGY_EXPERT',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_MULTI_SITE_RECOMMENDED',
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué variable caracteriza mejor una operación de alta energía?',
      '¿La evaluación futura debe variar por centro o por equipo crítico?',
      '¿Qué evidencia técnica y participación competente serían necesarias?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_CHEMICAL_PHARMA',
    name: 'Organización sintética química y farmacéutica',
    description:
      'Contexto sintético con proceso químico, alta energía y plantilla alta para validar decisiones concurrentes del DEMO pack.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Farmacéutica',
        workCenterCount: 1,
        workerCount: 80,
      },
      operations: { hasChemicalProcesses: true, hasHighEnergyOperations: true },
    },
    organizationContext: {
      summary: 'Laboratorio y producción sintéticos con sensibilidad de calidad elevada.',
      sizeHypothesis: 'LARGE',
      economicActivitySummary: 'Proceso químico y producción farmacéutica sintéticos.',
    },
    workCenters: [
      {
        workCenterId: 'CHEMICAL_LAB_PLANT',
        displayName: 'Centro sintético químico y de laboratorio',
        workerCount: 80,
        economicActivities: ['Proceso químico', 'Laboratorio', 'Producción farmacéutica'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'LABORATORY',
        operationalIndicators: [
          'CHEMICAL_HANDLING',
          'HIGH_ENERGY_EQUIPMENT',
          'CRITICAL_MACHINERY',
          'FIRE_LOAD',
        ],
      },
    ],
    operationalContext: {
      transportOperations: false,
      workAtHeight: false,
      contractors: true,
      criticalMachinery: true,
      fireExposure: true,
      electricityExposure: true,
      projectChanges: true,
      businessContinuityCriticality: 'HIGH',
      qualitySensitivity: 'HIGH',
      notes: ['El lab no interpreta normativa química, farmacéutica ni mediciones técnicas.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'MULTIPLE_ECONOMIC_ACTIVITIES',
      'CONTRACTORS',
      'CRITICAL_MACHINERY',
      'FIRE_EXPOSURE',
      'ELECTRICITY',
      'QUALITY_SENSITIVITY',
      'PROJECT_CHANGES',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'PRODUCT_OR_SERVICE_QUALITY',
      'MACHINERY_AND_INFRASTRUCTURE',
      'REPUTATION',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_CHEMICAL_CONTROL',
        implementationState: 'PARTIALLY_IMPLEMENTED',
        evidence: 'EXTERNAL_LINK_AVAILABLE',
        note: 'Referencia sintética no verificada; no prueba eficacia ni cumplimiento.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_3_SYSTEMIC_CHANGE_MANAGEMENT',
      rationale: 'La hipótesis futura requiere fuentes técnicas, cambios y seguimiento sistémico.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_CHEMICAL_MANDATORY',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NEEDS_EXPERT_REVIEW',
          winningRuleId: 'DEMO_HIGH_ENERGY_EXPERT',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué hechos adicionales son indispensables para analizar procesos químicos?',
      '¿Qué diferencias existen entre alcance organizacional y alcance de laboratorio?',
      '¿Qué fuentes técnicas deben preceder una futura regla real?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_UNKNOWN_INFORMATION',
    name: 'Organización sintética con información desconocida',
    description:
      'Escenario de un centro que omite intencionalmente plantilla, proceso químico y alta energía para ejercitar MISSING.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: { country: 'Ecuador', sector: 'Servicios', workCenterCount: 1 },
      operations: {},
    },
    organizationContext: {
      summary: 'Organización sintética con datos administrativos deliberadamente incompletos.',
      sizeHypothesis: 'SMALL',
      economicActivitySummary: 'Servicios sin detalle operativo suficiente.',
    },
    workCenters: [
      {
        workCenterId: 'UNKNOWN_CONTEXT_CENTER',
        displayName: 'Centro sintético con información pendiente',
        economicActivities: ['Servicios por validar'],
        riskClassificationHypothesis: 'UNKNOWN',
        facilityType: 'MIXED',
        operationalIndicators: [],
      },
    ],
    operationalContext: {
      transportOperations: false,
      workAtHeight: false,
      contractors: false,
      criticalMachinery: false,
      fireExposure: false,
      electricityExposure: false,
      projectChanges: false,
      businessContinuityCriticality: 'UNKNOWN',
      qualitySensitivity: 'UNKNOWN',
      notes: ['La ausencia de información se conserva; no se reemplaza con false o cero.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: ['PEOPLE_AND_HEALTH'],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_BASELINE_MANAGEMENT',
        implementationState: 'UNKNOWN',
        evidence: 'NO_EVIDENCE',
        note: 'Sin afirmación de implementación ni evidencia.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_1_VISIBLE_OPERATIONAL',
      rationale:
        'Hipótesis provisional que necesita más información antes de cualquier conclusión.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NEEDS_INFORMATION',
          winningRuleId: 'DEMO_CHEMICAL_MANDATORY',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NEEDS_INFORMATION',
          winningRuleId: 'DEMO_HIGH_ENERGY_EXPERT',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'OPTIONAL',
          winningRuleId: 'DEMO_SECTOR_OPTIONAL',
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'NEEDS_INFORMATION',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué pregunta debe priorizarse para resolver la falta de información?',
      '¿Qué datos pueden declararse a nivel organización y cuáles requieren centro?',
      '¿Cuándo debe intervenir una persona especialista?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_LOGISTICS_TRANSPORT',
    name: 'Organización sintética logística y de transporte',
    description:
      'Operación logística multi-centro donde transporte y flota se registran como contexto futuro no evaluado.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Logística',
        workCenterCount: 4,
        workerCount: 45,
      },
      operations: { hasChemicalProcesses: false, hasHighEnergyOperations: false },
    },
    organizationContext: {
      summary: 'Red logística sintética con bodegas, coordinación y operación de transporte.',
      sizeHypothesis: 'MEDIUM',
      economicActivitySummary: 'Logística, almacenamiento y transporte.',
    },
    workCenters: [
      {
        workCenterId: 'LOGISTICS_WAREHOUSE_A',
        displayName: 'Bodega sintética A',
        workerCount: 15,
        economicActivities: ['Almacenamiento'],
        riskClassificationHypothesis: 'MEDIUM',
        facilityType: 'WAREHOUSE',
        operationalIndicators: ['TRANSPORT_FLEET', 'FIRE_LOAD'],
      },
      {
        workCenterId: 'LOGISTICS_WAREHOUSE_B',
        displayName: 'Bodega sintética B',
        workerCount: 12,
        economicActivities: ['Despacho'],
        riskClassificationHypothesis: 'MEDIUM',
        facilityType: 'WAREHOUSE',
        operationalIndicators: ['TRANSPORT_FLEET'],
      },
      {
        workCenterId: 'LOGISTICS_HUB',
        displayName: 'Centro sintético de distribución',
        workerCount: 10,
        economicActivities: ['Distribución'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'WAREHOUSE',
        operationalIndicators: ['TRANSPORT_FLEET', 'CONTRACTOR_PRESENCE'],
      },
      {
        workCenterId: 'LOGISTICS_OFFICE',
        displayName: 'Centro sintético administrativo logístico',
        workerCount: 8,
        economicActivities: ['Administración logística'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: [],
      },
    ],
    operationalContext: {
      transportOperations: true,
      workAtHeight: false,
      contractors: true,
      criticalMachinery: false,
      fireExposure: true,
      electricityExposure: true,
      projectChanges: false,
      businessContinuityCriticality: 'HIGH',
      qualitySensitivity: 'MEDIUM',
      notes: ['Profile V1 no evalúa rutas, flota ni exposición por transporte.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'MULTIPLE_ECONOMIC_ACTIVITIES',
      'TRANSPORT_OPERATIONS',
      'CONTRACTORS',
      'FIRE_EXPOSURE',
      'BUSINESS_CONTINUITY',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'BUSINESS_CONTINUITY',
      'CONTRACTORS_AND_SUPPLY_CHAIN',
      'PRODUCTIVE_CONTINUITY',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_MULTI_SITE_COORDINATION',
        implementationState: 'PLANNED',
        evidence: 'SELF_DECLARED',
        note: 'Coordinación declarada sin verificación de evidencia ni eficacia.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_2_TECHNICAL_SOURCE_BASED',
      rationale: 'La operación de transporte requiere futura discusión técnica basada en fuentes.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_CHEMICAL_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_HIGH_ENERGY_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_MULTI_SITE_RECOMMENDED',
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué variables de transporte deberían añadirse al perfil futuro?',
      '¿La unidad de análisis debe ser ruta, centro, flota u organización?',
      '¿Qué profundidad requiere evidencia de continuidad y contratistas?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_CONSTRUCTION_CONTRACTORS',
    name: 'Organización sintética de construcción y contratistas',
    description:
      'Contexto de proyectos con trabajo en altura, contratistas y cambios, conservados como metadata no evaluada por Profile V1.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Construcción',
        workCenterCount: 2,
        workerCount: 18,
      },
      operations: { hasChemicalProcesses: false, hasHighEnergyOperations: true },
    },
    organizationContext: {
      summary: 'Proyectos sintéticos con contratistas y cambios frecuentes.',
      sizeHypothesis: 'MEDIUM',
      economicActivitySummary: 'Construcción y coordinación de contratistas.',
    },
    workCenters: [
      {
        workCenterId: 'CONSTRUCTION_PROJECT_A',
        displayName: 'Proyecto sintético de construcción A',
        workerCount: 10,
        economicActivities: ['Construcción'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'CONSTRUCTION_PROJECT',
        operationalIndicators: [
          'WORK_AT_HEIGHT',
          'CONTRACTOR_PRESENCE',
          'HIGH_ENERGY_EQUIPMENT',
          'PROJECT_CHANGE',
        ],
      },
      {
        workCenterId: 'CONSTRUCTION_PROJECT_B',
        displayName: 'Proyecto sintético de construcción B',
        workerCount: 8,
        economicActivities: ['Montaje'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'CONSTRUCTION_PROJECT',
        operationalIndicators: ['WORK_AT_HEIGHT', 'CONTRACTOR_PRESENCE', 'PROJECT_CHANGE'],
      },
    ],
    operationalContext: {
      transportOperations: true,
      workAtHeight: true,
      contractors: true,
      criticalMachinery: true,
      fireExposure: true,
      electricityExposure: true,
      projectChanges: true,
      businessContinuityCriticality: 'MEDIUM',
      qualitySensitivity: 'HIGH',
      notes: ['Trabajo en altura y contratistas no son predicados de Applicability V1.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'MULTIPLE_ECONOMIC_ACTIVITIES',
      'TRANSPORT_OPERATIONS',
      'WORK_AT_HEIGHT',
      'CONTRACTORS',
      'CRITICAL_MACHINERY',
      'FIRE_EXPOSURE',
      'ELECTRICITY',
      'PROJECT_CHANGES',
      'QUALITY_SENSITIVITY',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'CONTRACTORS_AND_SUPPLY_CHAIN',
      'PRODUCTIVE_CONTINUITY',
      'REPUTATION',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
        implementationState: 'IN_PROGRESS',
        evidence: 'NOTE_AVAILABLE',
        note: 'Hipótesis sintética de control en progreso, pendiente de verificación.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_3_SYSTEMIC_CHANGE_MANAGEMENT',
      rationale:
        'Contratistas y cambios de proyecto motivan discusión futura de MOC y seguimiento.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'NOT_APPLICABLE',
          winningRuleId: 'DEMO_CHEMICAL_NOT_APPLICABLE',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NEEDS_EXPERT_REVIEW',
          winningRuleId: 'DEMO_HIGH_ENERGY_EXPERT',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_MULTI_SITE_RECOMMENDED',
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'NOT_APPLICABLE',
          winningRuleId: null,
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Cómo separar alcance organizacional, proyecto y contratista?',
      '¿Qué eventos deberían activar un futuro flujo de Management of Change?',
      '¿Qué evidencia mínima permitiría validar el estado declarado?',
    ]),
  },
  {
    schemaVersion: '1.0.0',
    scenarioVersion: '1.0.0',
    id: 'EC_DEMO_MIXED_ACTIVITY_ENTERPRISE',
    name: 'Organización sintética grande de actividad mixta',
    description:
      'Empresa sintética multi-centro con actividades heterogéneas cuya proyección V1 colapsa diferencias por centro.',
    scenarioKind: 'SYNTHETIC',
    synthetic: true,
    profileV1Input: {
      schemaVersion: '1.0.0',
      organization: {
        country: 'Ecuador',
        sector: 'Tecnología',
        workCenterCount: 5,
        workerCount: 250,
      },
      operations: { hasChemicalProcesses: true, hasHighEnergyOperations: true },
    },
    organizationContext: {
      summary: 'Operación sintética grande con oficinas, bodegas, laboratorio y manufactura.',
      sizeHypothesis: 'LARGE',
      economicActivitySummary: 'Tecnología, manufactura, logística, laboratorio y servicios.',
    },
    workCenters: [
      {
        workCenterId: 'MIXED_HEAD_OFFICE',
        displayName: 'Centro sintético corporativo',
        workerCount: 60,
        economicActivities: ['Servicios', 'Tecnología'],
        riskClassificationHypothesis: 'LOW',
        facilityType: 'OFFICE',
        operationalIndicators: [],
      },
      {
        workCenterId: 'MIXED_MANUFACTURING',
        displayName: 'Centro sintético manufacturero',
        workerCount: 80,
        economicActivities: ['Manufactura'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'MANUFACTURING',
        operationalIndicators: ['HIGH_ENERGY_EQUIPMENT', 'CRITICAL_MACHINERY', 'FIRE_LOAD'],
      },
      {
        workCenterId: 'MIXED_LABORATORY',
        displayName: 'Laboratorio sintético',
        workerCount: 35,
        economicActivities: ['Laboratorio'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'LABORATORY',
        operationalIndicators: ['CHEMICAL_HANDLING', 'ELECTRICAL_EXPOSURE'],
      },
      {
        workCenterId: 'MIXED_WAREHOUSE',
        displayName: 'Bodega sintética',
        workerCount: 45,
        economicActivities: ['Almacenamiento', 'Distribución'],
        riskClassificationHypothesis: 'MEDIUM',
        facilityType: 'WAREHOUSE',
        operationalIndicators: ['TRANSPORT_FLEET', 'CONTRACTOR_PRESENCE'],
      },
      {
        workCenterId: 'MIXED_PROJECT',
        displayName: 'Proyecto sintético temporal',
        workerCount: 30,
        economicActivities: ['Montaje', 'Servicios técnicos'],
        riskClassificationHypothesis: 'HIGH',
        facilityType: 'CONSTRUCTION_PROJECT',
        operationalIndicators: ['WORK_AT_HEIGHT', 'CONTRACTOR_PRESENCE', 'PROJECT_CHANGE'],
      },
    ],
    operationalContext: {
      transportOperations: true,
      workAtHeight: true,
      contractors: true,
      criticalMachinery: true,
      fireExposure: true,
      electricityExposure: true,
      projectChanges: true,
      businessContinuityCriticality: 'HIGH',
      qualitySensitivity: 'HIGH',
      notes: ['Profile V1 reduce actividades heterogéneas a un sector organizacional.'],
    },
    futureContextNotEvaluated: [
      'WORKER_COUNT_BY_CENTER',
      'ECONOMIC_ACTIVITIES_BY_CENTER',
      'RISK_CLASSIFICATION_BY_CENTER',
      'FACILITY_TYPE',
      'MULTIPLE_ECONOMIC_ACTIVITIES',
      'TRANSPORT_OPERATIONS',
      'WORK_AT_HEIGHT',
      'CONTRACTORS',
      'CRITICAL_MACHINERY',
      'FIRE_EXPOSURE',
      'ELECTRICITY',
      'BUSINESS_CONTINUITY',
      'QUALITY_SENSITIVITY',
      'PROJECT_CHANGES',
      'STRATEGIC_PROTECTION_PRIORITIES',
      'CURRENT_STATE_CONTROLS',
      'EVIDENCE_AVAILABILITY',
      'DESIRED_INSPECTION_DEPTH',
    ],
    strategicProtectionPriorities: [
      'PEOPLE_AND_HEALTH',
      'PRODUCTIVE_CONTINUITY',
      'BUSINESS_CONTINUITY',
      'MACHINERY_AND_INFRASTRUCTURE',
      'FINANCIAL_IMPACT',
      'REPUTATION',
      'CONTRACTORS_AND_SUPPLY_CHAIN',
      'PRODUCT_OR_SERVICE_QUALITY',
    ],
    currentStateHypotheses: [
      {
        targetKey: 'DEMO_BASELINE_MANAGEMENT',
        implementationState: 'PARTIALLY_IMPLEMENTED',
        evidence: 'SELF_DECLARED',
        note: 'El estado puede variar entre centros y no prueba cumplimiento.',
      },
      {
        targetKey: 'DEMO_CHEMICAL_CONTROL',
        implementationState: 'PLANNED',
        evidence: 'NOTE_AVAILABLE',
        note: 'La hipótesis del laboratorio no modifica la aplicabilidad histórica.',
      },
    ],
    depthHypothesis: {
      level: 'LEVEL_3_SYSTEMIC_CHANGE_MANAGEMENT',
      rationale:
        'La heterogeneidad y los cambios requieren una futura resolución por centro y sistema.',
    },
    engineExpectation: {
      basis: 'DEMO_APPLICABILITY_V1_0_0',
      decisions: [
        {
          targetKey: 'DEMO_BASELINE_MANAGEMENT',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_BASELINE_MANDATORY',
        },
        {
          targetKey: 'DEMO_CHEMICAL_CONTROL',
          state: 'MANDATORY',
          winningRuleId: 'DEMO_CHEMICAL_MANDATORY',
        },
        {
          targetKey: 'DEMO_HIGH_ENERGY_REVIEW',
          state: 'NEEDS_EXPERT_REVIEW',
          winningRuleId: 'DEMO_HIGH_ENERGY_EXPERT',
        },
        {
          targetKey: 'DEMO_MULTI_SITE_COORDINATION',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_MULTI_SITE_RECOMMENDED',
        },
        {
          targetKey: 'DEMO_SECTOR_GUIDANCE',
          state: 'OPTIONAL',
          winningRuleId: 'DEMO_SECTOR_OPTIONAL',
        },
        {
          targetKey: 'DEMO_WORKFORCE_GUIDANCE',
          state: 'RECOMMENDED',
          winningRuleId: 'DEMO_WORKFORCE_RECOMMENDED',
        },
      ],
    },
    expertValidation: pendingExpert([
      '¿Qué información debe conservarse por centro para evitar la pérdida de contexto?',
      '¿Cómo priorizar sin alterar aplicabilidad ni profundidad mínima?',
      '¿Qué baseline actual debe capturarse antes de calcular futuros gaps?',
    ]),
  },
];

export const COMMITTED_SST_SCENARIOS = Object.freeze(
  scenarioInputs.map((scenario) => sstValidationScenarioSchema.parse(scenario)),
);

export const SST_SCENARIOS_BY_ID = new Map(
  COMMITTED_SST_SCENARIOS.map((scenario) => [scenario.id, scenario] as const),
);
