export const INSPECTION_RESOURCE_PROPOSAL_ROLES = [
  'ORG_OWNER',
  'ORG_ADMIN',
  'SST_MANAGER',
  'SST_TECHNICIAN',
  'CONSULTANT',
] as const;

export const INSPECTION_RESOURCE_REVIEW_ROLES = ['ORG_OWNER', 'ORG_ADMIN', 'SST_MANAGER'] as const;
